### ISSUE TITLE
[scraper-tests] test_extract_skill failed - IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by samarth-p** [TejasPrabhu/Job-Analyzer#40]
Run link: https://github.com/TejasPrabhu/Job-Analyzer/actions/runs/3215523525/jobs/5256677699

![image](https://user-images.githubusercontent.com/42717178/194779122-2dac5b0e-d176-4abb-967f-43872f0ee40e.png)

**Comment by Naveen-Jayanna** [comment]
One of the other tests was overwriting linkedin_scraper.csv. Modified that test to not update the csv. Tests are passing now

![image](https://user-images.githubusercontent.com/52947925/194797897-9034708f-046c-4ee2-bd9b-dcdc059b7ca0.png)
