### ISSUE TITLE
pytest failed:[ModuleNotFoundError: No module named 'app']

### ISSUE THREAD

**Issue by Naveen-Jayanna** [TejasPrabhu/Job-Analyzer#41]
https://github.com/TejasPrabhu/Job-Analyzer/actions/runs/3215762079/jobs/5257085830

![image](https://user-images.githubusercontent.com/52947925/194782220-13c6fe2f-cd73-428f-b703-89ebc11e125e.png)

**Comment by samarth-p** [comment]
An issue with relative import. changed it as follows -

`from src.app import add, mongodb_client`
